INSERT INTO public.users VALUES (1, True, 'admin@gmail.com', '$2a$10$E2.PwtnpF2p6aB3NFM3Qo.TarTYsaiWD0yTZ7qY1U3K.ybKxNvCku');
INSERT INTO public.users VALUES (2, True, 'cowner@gmail.com', '$2a$10$DmeWO6UlY/m2QjJaxLGUzezqOotvJmpzbBmZGBr8o/HHeNUuCWcpK');
INSERT INTO public.users VALUES (3, True, 'user@gmail.com', '$2a$10$t31PsVNWl8eaWr9/gPwKKeX.4Q2grl12wmiRrN9fEZDMlMGHwA92m');
INSERT INTO public.users VALUES (11, True, 'rabotynet.test.fp@gmail.com', '$2a$10$c0a3HsdYm6VHO9h1/ZXWg.qDqWve8GghCpCA7iRXlE7PyE3dyeaWi');
INSERT INTO public.contact VALUES (1, 'den.ohorodnik@gmail.com', '+380973999060');
INSERT INTO public.contact VALUES (2, 'jon.snow@gmail.com', '+380973219033');
INSERT INTO public.contact VALUES (3, 'softserve.inc@gmail.com', '+380322409999');
INSERT INTO public.contact VALUES (4, 'inventorsoft.inc@gmail.com', '+380984529012');
INSERT INTO public.contact VALUES (5, 'valsoft@gmail.com', '+380972993270');
INSERT INTO public.contact VALUES (13, 'rabotynet.test.fp@gmail.com', Null);
INSERT INTO public.address VALUES (1, Null, '20', 'Chernivtsi', 'Ukraine', 'Holovna', 58000);
INSERT INTO public.address VALUES (2, Null, '33', 'Chernivtsi', 'Ukraine', 'Shevchenka', 58000);
INSERT INTO public.address VALUES (3, Null, '246', 'Chernivtsi', 'Ukraine', 'Holovna', 58000);
INSERT INTO public.address VALUES (4, Null, '33', 'Chernivtsi', 'Ukraine', 'Komarova', 58000);
INSERT INTO public.address VALUES (5, Null, '15', 'Chernivtsi', 'Ukraine', 'Rivnenska', 58000);
INSERT INTO public.company VALUES (1, 'We are digital advisors and providers who operate at the cutting edge of technology. We deliver the innovation, quality, and speed that our clients’ users expect.', '23456742', 'SoftServe', 'APPROVED', 'www.softserveinc.com', 3, 3, Null, 2);
INSERT INTO public.company VALUES (2, 'Second company', '55368632', 'InventorSoft', 'CREATED', 'www.inventorsoft.com', 4, 4, Null, 2);
INSERT INTO public.company VALUES (3, 'Third company', '63964221', 'ValSoft', 'BLOCKED', 'www.valsoft.com', 5, 5, Null, 2);
INSERT INTO public.education VALUES (1, 'Master', 2016, 'ChNU', 'Software Engineer');
INSERT INTO public.education VALUES (2, 'Master', 2009, 'KPI', 'Software Engineer');
INSERT INTO public.person VALUES (1, Null, Null, Null, Null, Null, Null);
INSERT INTO public.person VALUES (2, '1986-11-26', 'Jon', 'Snow', 2, 2, Null);
INSERT INTO public.person VALUES (3, '1999-6-4', 'Denys', 'Ohorodnik', 1, 1, Null);
INSERT INTO public.person VALUES (11, Null, Null, Null, Null, 13, Null);
INSERT INTO public.resume VALUES (1, 'Junior Developer', False, 1, 2);
INSERT INTO public.resume VALUES (2, 'Middle Developer', False, 2, 3);
INSERT INTO public.roles VALUES (1, 'admin');
INSERT INTO public.roles VALUES (2, 'cowner');
INSERT INTO public.roles VALUES (3, 'user');
INSERT INTO public.job VALUES (1, '2000-10-10', 'SoftServe', 'Junior Java Developer', '2009-3-4', 'Junior', True, 1);
INSERT INTO public.job VALUES (2, '2006-4-8', 'ValSoft', 'Middle Java Developer', '2009-11-4', 'Middle', True, 1);
INSERT INTO public.job VALUES (3, '2008-3-8', 'ValSoft', 'Middle Java developer', '2005-7-4', 'Middle', True, 2);
INSERT INTO public.job VALUES (4, '2006-10-8', 'SoftServe', 'Junior Java Developer', '2009-10-4', 'Junior', True, 2);
INSERT INTO public.job VALUES (5, '2010-4-8', 'InventorSoft', 'Senior Java Developer', '2014-11-4', 'Senior', True, 2);
INSERT INTO public.vacancy VALUES (1, 'USD', 'Junior Java Developer', 'FULL', False, 'Junior Developer', 1000, 'OCCUPIED', 1);
INSERT INTO public.vacancy VALUES (2, 'UAH', 'Middle React Developer', 'HOURLY', False, 'Middle Developer', 3000, 'OUTDATED', 1);
INSERT INTO public.vacancy VALUES (3, 'UAH', 'Senior Angular Developer', 'PART_TIME', False, 'Senior Developer', 4000, 'OUTDATED', 1);
INSERT INTO public.vacancy VALUES (4, 'EUR', 'Junior Junior Developer', 'FULL', False, 'Junior Developer', 1000, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (5, 'EUR', 'Middle WebUI Developer', 'HOURLY', False, 'Middle Developer', 3000, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (6, 'USD', 'Senior Angular Developer', 'PART_TIME', True, 'Senior Developer', 4000, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (7, 'USD', 'Junior Java Developer', 'FULL', False, 'Junior Developer', 1000, 'OPEN', 3);
INSERT INTO public.vacancy VALUES (8, 'UAH', 'Middle WebUI Developer', 'HOURLY', True, 'Middle Developer', 3000, 'OPEN', 3);
INSERT INTO public.vacancy VALUES (9, 'EUR', 'Senior React Developer', 'PART_TIME', True, 'Senior Developer', 4000, 'OPEN', 3);
INSERT INTO public.vacancy VALUES (10, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (11, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (12, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (13, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (14, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (15, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (16, 'USD', 'Junior ATQC Engineer', 'FULL', Null, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (17, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (18, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (19, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (20, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (21, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (22, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (23, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (24, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (25, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (26, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (27, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (28, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (29, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (30, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (31, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (32, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (33, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.vacancy VALUES (34, 'USD', 'Junior ATQC Engineer', 'FULL', True, 'Junior Engineer', 450, 'OPEN', 1);
INSERT INTO public.requirement VALUES (1, 'Problem-solving skills', 1);
INSERT INTO public.requirement VALUES (2, 'Good knowledge of PostgreSQL, JUnit, bash, ant, Linux', 1);
INSERT INTO public.requirement VALUES (3, 'Strong organizational and leadership skills', 2);
INSERT INTO public.requirement VALUES (4, 'Proven experience as a Java Software Engineer, Java Developer or similar role', 2);
INSERT INTO public.requirement VALUES (5, 'Strong experience building Java EE applications, preferably using Java 8', 3);
INSERT INTO public.requirement VALUES (6, 'Degree in Computer Science, Engineering or relevant field', 3);
INSERT INTO public.requirement VALUES (7, 'Bachelor degree in computer science or related fields', 4);
INSERT INTO public.requirement VALUES (8, 'Ability to program production-grade applications with Node.js', 4);
INSERT INTO public.requirement VALUES (9, 'Solid understanding of Linux operating system', 5);
INSERT INTO public.requirement VALUES (10, 'Good understanding of the networking', 5);
INSERT INTO public.requirement VALUES (11, 'Experience with any public cloud provider', 6);
INSERT INTO public.requirement VALUES (12, 'Experience in and understanding of CI', 6);
INSERT INTO public.requirement VALUES (13, 'Experience with monitoring and log management ', 7);
INSERT INTO public.requirement VALUES (14, 'Degree in Computer Science, Engineering or relevant field', 7);
INSERT INTO public.requirement VALUES (15, 'Extensive understanding of enterprise monitoring solutions', 8);
INSERT INTO public.requirement VALUES (16, 'Good written and verbal English communications skills', 8);
INSERT INTO public.requirement VALUES (17, 'Deep knowledge DBs, RDBMS, SQL', 9);
INSERT INTO public.requirement VALUES (18, 'You are adept at writing unit tests and testable code, and working under distributed version control', 9);
INSERT INTO public.requirement VALUES (19, 'Fundamental understanding of testing process', 10);
INSERT INTO public.requirement VALUES (20, 'Good knowledge of Python', 10);
INSERT INTO public.requirement VALUES (21, 'Fundamental understanding of testing process', 11);
INSERT INTO public.requirement VALUES (22, 'Good knowledge of Python', 11);
INSERT INTO public.requirement VALUES (23, 'Fundamental understanding of testing process', 12);
INSERT INTO public.requirement VALUES (24, 'Good knowledge of Python', 12);
INSERT INTO public.requirement VALUES (25, 'Good knowledge of Python', 13);
INSERT INTO public.requirement VALUES (26, 'Fundamental understanding of testing process', 13);
INSERT INTO public.requirement VALUES (27, 'Good knowledge of Python', 14);
INSERT INTO public.requirement VALUES (28, 'Fundamental understanding of testing process', 14);
INSERT INTO public.requirement VALUES (29, 'Good knowledge of Python', 15);
INSERT INTO public.requirement VALUES (30, 'Fundamental understanding of testing process', 15);
INSERT INTO public.requirement VALUES (31, 'Good knowledge of Python', 16);
INSERT INTO public.requirement VALUES (32, 'Fundamental understanding of testing process', 16);
INSERT INTO public.requirement VALUES (33, 'Fundamental understanding of testing process', 17);
INSERT INTO public.requirement VALUES (34, 'Good knowledge of Python', 17);
INSERT INTO public.requirement VALUES (35, 'Fundamental understanding of testing process', 18);
INSERT INTO public.requirement VALUES (36, 'Good knowledge of Python', 18);
INSERT INTO public.requirement VALUES (37, 'Good knowledge of Python', 19);
INSERT INTO public.requirement VALUES (38, 'Fundamental understanding of testing process', 19);
INSERT INTO public.requirement VALUES (39, 'Good knowledge of Python', 20);
INSERT INTO public.requirement VALUES (40, 'Fundamental understanding of testing process', 20);
INSERT INTO public.requirement VALUES (41, 'Good knowledge of Python', 21);
INSERT INTO public.requirement VALUES (42, 'Fundamental understanding of testing process', 21);
INSERT INTO public.requirement VALUES (43, 'Fundamental understanding of testing process', 22);
INSERT INTO public.requirement VALUES (44, 'Good knowledge of Python', 22);
INSERT INTO public.requirement VALUES (45, 'Good knowledge of Python', 23);
INSERT INTO public.requirement VALUES (46, 'Fundamental understanding of testing process', 23);
INSERT INTO public.requirement VALUES (47, 'Fundamental understanding of testing process', 24);
INSERT INTO public.requirement VALUES (48, 'Good knowledge of Python', 24);
INSERT INTO public.requirement VALUES (49, 'Good knowledge of Python', 25);
INSERT INTO public.requirement VALUES (50, 'Fundamental understanding of testing process', 25);
INSERT INTO public.requirement VALUES (51, 'Fundamental understanding of testing process', 26);
INSERT INTO public.requirement VALUES (52, 'Good knowledge of Python', 26);
INSERT INTO public.requirement VALUES (53, 'Fundamental understanding of testing process', 27);
INSERT INTO public.requirement VALUES (54, 'Good knowledge of Python', 27);
INSERT INTO public.requirement VALUES (55, 'Good knowledge of Python', 28);
INSERT INTO public.requirement VALUES (56, 'Fundamental understanding of testing process', 28);
INSERT INTO public.requirement VALUES (57, 'Fundamental understanding of testing process', 29);
INSERT INTO public.requirement VALUES (58, 'Good knowledge of Python', 29);
INSERT INTO public.requirement VALUES (59, 'Good knowledge of Python', 30);
INSERT INTO public.requirement VALUES (60, 'Fundamental understanding of testing process', 30);
INSERT INTO public.requirement VALUES (61, 'Good knowledge of Python', 31);
INSERT INTO public.requirement VALUES (62, 'Fundamental understanding of testing process', 31);
INSERT INTO public.requirement VALUES (63, 'Good knowledge of Python', 32);
INSERT INTO public.requirement VALUES (64, 'Fundamental understanding of testing process', 32);
INSERT INTO public.requirement VALUES (65, 'Good knowledge of Python', 33);
INSERT INTO public.requirement VALUES (66, 'Fundamental understanding of testing process', 33);
INSERT INTO public.requirement VALUES (67, 'Good knowledge of Python', 34);
INSERT INTO public.requirement VALUES (68, 'Fundamental understanding of testing process', 34);
INSERT INTO public.skill VALUES (1, 'Spring MVC', True, 'MVC', 1);
INSERT INTO public.skill VALUES (2, 'Spring Boot', True, 'Spring', 1);
INSERT INTO public.skill VALUES (3, 'Good skill', True, 'Linux', 2);
INSERT INTO public.skill VALUES (4, 'Some experience', True, 'Angular', 2);
INSERT INTO public.skill VALUES (5, 'Some experience', True, 'Html', 2);
INSERT INTO public.user_role VALUES (1, 1);
INSERT INTO public.user_role VALUES (2, 2);
INSERT INTO public.user_role VALUES (2, 3);
INSERT INTO public.user_role VALUES (3, 3);
INSERT INTO public.user_role VALUES (11, 3);
